all: Main.java Dorms.java SafeEntry.java PersonDatabase.java LocationDatabase.java Person.java MaskedPerson.java Location.java Contact.java Virus.java AlphaCoronavirus.java BetaCoronavirus.java SARS_CoV_2.java
	javac *.java

clean:
	rm *.class
